<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet id (amino-acid|nucleotide) #REQUIRED
                   length CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.9.1" release="Fri Aug 23 16:49:42 2013 +1000">
<training_set datafile="downreg-seqs-safe.top100.fasta" length="100">
<alphabet id="nucleotide" length="4">
<letter id="letter_A" symbol="A"/>
<letter id="letter_C" symbol="C"/>
<letter id="letter_G" symbol="G"/>
<letter id="letter_T" symbol="T"/>
</alphabet>
<ambigs>
<letter id="letter_B" symbol="B"/>
<letter id="letter_D" symbol="D"/>
<letter id="letter_H" symbol="H"/>
<letter id="letter_K" symbol="K"/>
<letter id="letter_M" symbol="M"/>
<letter id="letter_N" symbol="N"/>
<letter id="letter_R" symbol="R"/>
<letter id="letter_S" symbol="S"/>
<letter id="letter_U" symbol="U"/>
<letter id="letter_V" symbol="V"/>
<letter id="letter_W" symbol="W"/>
<letter id="letter_Y" symbol="Y"/>
<letter id="letter_star" symbol="*"/>
<letter id="letter_-" symbol="-"/>
<letter id="letter_X" symbol="X"/>
</ambigs>
<sequence id="sequence_0" name="CPVL" length="1500" weight="1.000000" />
<sequence id="sequence_1" name="GPR162" length="1500" weight="1.000000" />
<sequence id="sequence_2" name="PAK1" length="1500" weight="1.000000" />
<sequence id="sequence_3" name="CD36" length="1500" weight="1.000000" />
<sequence id="sequence_4" name="CST3" length="1500" weight="1.000000" />
<sequence id="sequence_5" name="ZNF185" length="1500" weight="1.000000" />
<sequence id="sequence_6" name="ZNF467" length="1500" weight="1.000000" />
<sequence id="sequence_7" name="MS4A6A" length="1500" weight="1.000000" />
<sequence id="sequence_8" name="RXRA" length="1500" weight="1.000000" />
<sequence id="sequence_9" name="SULF2" length="1500" weight="1.000000" />
<sequence id="sequence_10" name="RBP7" length="1500" weight="1.000000" />
<sequence id="sequence_11" name="FGL2" length="1500" weight="1.000000" />
<sequence id="sequence_12" name="PYGL" length="1500" weight="1.000000" />
<sequence id="sequence_13" name="OPRL1" length="1500" weight="1.000000" />
<sequence id="sequence_14" name="GAS7" length="1500" weight="1.000000" />
<sequence id="sequence_15" name="PLOD1" length="1500" weight="1.000000" />
<sequence id="sequence_16" name="HLA-DMA" length="1500" weight="1.000000" />
<sequence id="sequence_17" name="UBAC1" length="1500" weight="1.000000" />
<sequence id="sequence_18" name="TST" length="1500" weight="1.000000" />
<sequence id="sequence_19" name="FCGR3B" length="1500" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="letter_A">0.235</value>
<value letter_id="letter_C">0.265</value>
<value letter_id="letter_G">0.265</value>
<value letter_id="letter_T">0.235</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme downreg-seqs-safe.top100.fasta -dna -oc . -nmotifs 8 -mod zoops -maxsize 170000 -minw 20 -maxw 50 -revcomp -psp down-vs-control.priors </command_line>
<host>wpga-pagapow</host>
<type>zoops</type>
<nmotifs>8</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<min_width>20</min_width>
<max_width>50</max_width>
<minic>    0.00</minic>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<minsites>2</minsites>
<maxsites>100</maxsites>
<wnsites>0.8</wnsites>
<prob>1</prob>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>100</num_sequences>
<num_positions>150000</num_positions>
<seed>0</seed>
<seqfrac>       1</seqfrac>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because nmotifs = 8 reached.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="letter_A">0.235</value>
<value letter_id="letter_C">0.265</value>
<value letter_id="letter_G">0.265</value>
<value letter_id="letter_T">0.235</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="50" sites="48" ic="74.3" re="74.0" llr="2461" e_value="3.2e-748" bayes_threshold="11.2201" elapsed_time="634.980660">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">185</value>
<value letter_id="letter_G">-367</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-349</value>
<value letter_id="letter_C">182</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-249</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-349</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">203</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-149</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">176</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">-208</value>
<value letter_id="letter_G">-367</value>
<value letter_id="letter_T">196</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">196</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">-267</value>
<value letter_id="letter_T">-249</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">136</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">58</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">-267</value>
<value letter_id="letter_G">-367</value>
<value letter_id="letter_T">200</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">176</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-117</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">192</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-349</value>
<value letter_id="letter_C">182</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-249</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">206</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">-367</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">185</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-349</value>
<value letter_id="letter_C">185</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-69</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">183</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">183</value>
<value letter_id="letter_C">-108</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-249</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">162</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-33</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">-367</value>
<value letter_id="letter_T">200</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">128</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">41</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">41</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">124</value>
<value letter_id="letter_T">-191</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">182</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-349</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">189</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">206</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">185</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">185</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-349</value>
<value letter_id="letter_C">185</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">-167</value>
<value letter_id="letter_G">-208</value>
<value letter_id="letter_T">186</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">185</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">209</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-349</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">182</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-117</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">169</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">142</value>
<value letter_id="letter_G">-367</value>
<value letter_id="letter_T">20</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">179</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">-50</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-349</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">185</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">189</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">206</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">182</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">163</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">-8</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">209</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">-267</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">203</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">85</value>
<value letter_id="letter_G">-8</value>
<value letter_id="letter_T">20</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-4</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">142</value>
<value letter_id="letter_T">-249</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">172</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-91</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">-208</value>
<value letter_id="letter_G">-67</value>
<value letter_id="letter_T">163</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-1223</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">-367</value>
<value letter_id="letter_T">203</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">182</value>
<value letter_id="letter_T">-349</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">203</value>
<value letter_id="letter_C">-1223</value>
<value letter_id="letter_G">-267</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">167</value>
<value letter_id="letter_C">-367</value>
<value letter_id="letter_G">-21</value>
<value letter_id="letter_T">-1223</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-191</value>
<value letter_id="letter_C">169</value>
<value letter_id="letter_G">-267</value>
<value letter_id="letter_T">-249</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-249</value>
<value letter_id="letter_C">172</value>
<value letter_id="letter_G">-1223</value>
<value letter_id="letter_T">-149</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.958333</value>
<value letter_id="letter_G">0.020833</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.020833</value>
<value letter_id="letter_C">0.937500</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.041667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.020833</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.958333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.083333</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.895833</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.062500</value>
<value letter_id="letter_G">0.020833</value>
<value letter_id="letter_T">0.916667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.916667</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.041667</value>
<value letter_id="letter_T">0.041667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.604167</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.395833</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.041667</value>
<value letter_id="letter_G">0.020833</value>
<value letter_id="letter_T">0.937500</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.895833</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.104167</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">1.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.020833</value>
<value letter_id="letter_C">0.937500</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.041667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.979167</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.020833</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.958333</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.020833</value>
<value letter_id="letter_C">0.958333</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.145833</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.833333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.833333</value>
<value letter_id="letter_C">0.125000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.041667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.812500</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.187500</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.020833</value>
<value letter_id="letter_T">0.937500</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.645833</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.312500</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.312500</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.625000</value>
<value letter_id="letter_T">0.062500</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.937500</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.020833</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.979167</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.979167</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.958333</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.958333</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.020833</value>
<value letter_id="letter_C">0.958333</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.083333</value>
<value letter_id="letter_G">0.062500</value>
<value letter_id="letter_T">0.854167</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.958333</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">1.000000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.020833</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.937500</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.104167</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.854167</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.708333</value>
<value letter_id="letter_G">0.020833</value>
<value letter_id="letter_T">0.270833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.812500</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.187500</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.020833</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.958333</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.979167</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.979167</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.937500</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.729167</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.250000</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">1.000000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.041667</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.958333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.479167</value>
<value letter_id="letter_G">0.250000</value>
<value letter_id="letter_T">0.270833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.229167</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.708333</value>
<value letter_id="letter_T">0.041667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.875000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.125000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.062500</value>
<value letter_id="letter_G">0.166667</value>
<value letter_id="letter_T">0.729167</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.000000</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.020833</value>
<value letter_id="letter_T">0.958333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.937500</value>
<value letter_id="letter_T">0.020833</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.958333</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.041667</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.750000</value>
<value letter_id="letter_C">0.020833</value>
<value letter_id="letter_G">0.229167</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.062500</value>
<value letter_id="letter_C">0.854167</value>
<value letter_id="letter_G">0.041667</value>
<value letter_id="letter_T">0.041667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.041667</value>
<value letter_id="letter_C">0.875000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.083333</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
CCTGTA[AG]TCCCAGCTACT[CT][GA]GGAGGCTGAGG[CT]AGGAG[AG]AT[CTG][GA]CTTGA[AG]CC
</regular_expression>
<contributing_sites>